/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as UserRouteImport } from './routes/_user'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminInternshipsRouteImport } from './routes/admin.internships'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as UserSearchRouteImport } from './routes/_user.search'
import { Route as UserProfileRouteImport } from './routes/_user.profile'
import { Route as UserDocumentsRouteImport } from './routes/_user.documents'
import { Route as UserDashboardRouteImport } from './routes/_user.dashboard'
import { Route as UserContentRouteImport } from './routes/_user.content'
import { Route as UserCareersRouteImport } from './routes/_user.careers'
import { Route as UserAnalyticsRouteImport } from './routes/_user.analytics'
import { Route as UserAiQueryRouteImport } from './routes/_user.ai-query'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInternshipsRoute = AdminInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const UserSearchRoute = UserSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserDocumentsRoute = UserDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => UserRoute,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => UserRoute,
} as any)
const UserContentRoute = UserContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => UserRoute,
} as any)
const UserCareersRoute = UserCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => UserRoute,
} as any)
const UserAnalyticsRoute = UserAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => UserRoute,
} as any)
const UserAiQueryRoute = UserAiQueryRouteImport.update({
  id: '/ai-query',
  path: '/ai-query',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-query': typeof UserAiQueryRoute
  '/analytics': typeof UserAnalyticsRoute
  '/careers': typeof UserCareersRoute
  '/content': typeof UserContentRoute
  '/dashboard': typeof UserDashboardRoute
  '/documents': typeof UserDocumentsRoute
  '/profile': typeof UserProfileRoute
  '/search': typeof UserSearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-query': typeof UserAiQueryRoute
  '/analytics': typeof UserAnalyticsRoute
  '/careers': typeof UserCareersRoute
  '/content': typeof UserContentRoute
  '/dashboard': typeof UserDashboardRoute
  '/documents': typeof UserDocumentsRoute
  '/profile': typeof UserProfileRoute
  '/search': typeof UserSearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_user': typeof UserRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_user/ai-query': typeof UserAiQueryRoute
  '/_user/analytics': typeof UserAnalyticsRoute
  '/_user/careers': typeof UserCareersRoute
  '/_user/content': typeof UserContentRoute
  '/_user/dashboard': typeof UserDashboardRoute
  '/_user/documents': typeof UserDocumentsRoute
  '/_user/profile': typeof UserProfileRoute
  '/_user/search': typeof UserSearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/internships': typeof AdminInternshipsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-query'
    | '/analytics'
    | '/careers'
    | '/content'
    | '/dashboard'
    | '/documents'
    | '/profile'
    | '/search'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/internships'
    | '/admin/news'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-query'
    | '/analytics'
    | '/careers'
    | '/content'
    | '/dashboard'
    | '/documents'
    | '/profile'
    | '/search'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/internships'
    | '/admin/news'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/admin'
    | '/_user/ai-query'
    | '/_user/analytics'
    | '/_user/careers'
    | '/_user/content'
    | '/_user/dashboard'
    | '/_user/documents'
    | '/_user/profile'
    | '/_user/search'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/internships'
    | '/admin/news'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UserRoute: typeof UserRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/internships': {
      id: '/admin/internships'
      path: '/internships'
      fullPath: '/admin/internships'
      preLoaderRoute: typeof AdminInternshipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_user/search': {
      id: '/_user/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof UserSearchRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/profile': {
      id: '/_user/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/documents': {
      id: '/_user/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof UserDocumentsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/dashboard': {
      id: '/_user/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/content': {
      id: '/_user/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof UserContentRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/careers': {
      id: '/_user/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof UserCareersRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/analytics': {
      id: '/_user/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof UserAnalyticsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/ai-query': {
      id: '/_user/ai-query'
      path: '/ai-query'
      fullPath: '/ai-query'
      preLoaderRoute: typeof UserAiQueryRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface UserRouteChildren {
  UserAiQueryRoute: typeof UserAiQueryRoute
  UserAnalyticsRoute: typeof UserAnalyticsRoute
  UserCareersRoute: typeof UserCareersRoute
  UserContentRoute: typeof UserContentRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserDocumentsRoute: typeof UserDocumentsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserSearchRoute: typeof UserSearchRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserAiQueryRoute: UserAiQueryRoute,
  UserAnalyticsRoute: UserAnalyticsRoute,
  UserCareersRoute: UserCareersRoute,
  UserContentRoute: UserContentRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserDocumentsRoute: UserDocumentsRoute,
  UserProfileRoute: UserProfileRoute,
  UserSearchRoute: UserSearchRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminInternshipsRoute: typeof AdminInternshipsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminInternshipsRoute: AdminInternshipsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
